# Generated by Django 3.2.5 on 2023-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date_of_birth',
            field=models.IntegerField(default=1990),
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(choices=[('ENG', 'Великобритания'), ('RUS', 'Россия'), ('KZ', 'Казахстан'), ('CH', 'Китай'), ('GER', 'Германия')], default=('KZ', 'Казахстан'), max_length=25),
        ),
        migrations.AlterField(
            model_name='auto',
            name='owners',
            field=models.ManyToManyField(related_name='autos', through='api.OwnerAuto', to='api.Owner'),
        ),
    ]
