# Generated by Django 3.2.5 on 2023-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230326_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='nationality',
            field=models.CharField(choices=[('ENG', 'Великобритания'), ('RUS', 'Россия'), ('KZ', 'Казахстан'), ('CH', 'Китай'), ('GER', 'Германия')], default='Казахстан', max_length=25),
        ),
    ]
