# Generated by Django 4.1.7 on 2023-03-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_purchase_ownerauto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerauto',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='ownerauto',
            name='purchase_price',
        ),
    ]
