# Generated by Django 3.2.5 on 2023-03-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ownerauto_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerauto',
            old_name='car',
            new_name='auto',
        ),
    ]
